import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { name: "Home", href: "/" },
  { name: "Interviews", href: "/interviews" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {
        links. map((link) =>
        {
          return (
            <div key={link.name}>
              <Link key={link.name} href={link.href}>{link.name}</Link>
            </div>
          )
        })
      }
      <body className={inter.className}>{children}</body>
    </html>
  );
}
