
import { defineStore } from 'pinia';
import { Task } from '../../interfaces/task.interface';
import { Comment } from '../../interfaces/comment.interface';
import { UserStat } from '../../interfaces/user-stat.interface'; 

export interface UserProfile {
    id: number;
    username: string;
    email: string;
    password: string;
  }

export const useStore = defineStore({
  id: 'main',
  state: () => ({
    userStats: [
        {
          userId: 1,
          tasksSolved: "25",
          rating: 4.7,
          description: "Старший разработчик с 8-летним опытом",
          fio: "Джон Смит",
          position: "Старший инженер-программист",
          age: 35
        },
        {
          userId: 2,
          tasksSolved: "18",
          rating: 4.2,
          description: "Фронтенд-разработчик, специализирующийся на React и Vue.js",
          fio: "Алиса Джонсон",
          position: "Фронтенд-разработчик",
          age: 28
        },
        {
          userId: 3,
          tasksSolved: "30",
          rating: 4.9,
          description: "Бэкенд-разработчик с опытом работы на Node.js и MongoDB",
          fio: "Андрей Браун",
          position: "Бэкенд-разработчик",
          age: 32
        },
        {
          userId: 4,
          tasksSolved: "12",
          rating: 3.8,
          description: "Младший разработчик, стремящийся учиться и развиваться",
          fio: "Эмма Уилсон",
          position: "Младший инженер-программист",
          age: 25
        },
        {
          userId: 5,
          tasksSolved: "40",
          rating: 5.0,
          description: "Full-stack разработчик с опытом работы в React, Node.js и AWS",
          fio: "Майкл Дэвис",
          position: "Full-stack разработчик",
          age: 30
        },
        {
          userId: 6,
          tasksSolved: "22",
          rating: 4.5,
          description: "Инженер-программист с увлечением в области data science и машинного обучения",
          fio: "Оливия Мартинес",
          position: "Инженер-программист",
          age: 29
        },
        {
          userId: 7,
          tasksSolved: "15",
          rating: 4.0,
          description: "UI/UX дизайнер, создающий красивые и интуитивно понятные пользовательские интерфейсы",
          fio: "Даниэль Уайт",
          position: "UI/UX дизайнер",
          age: 27
        },
        {
          userId: 8,
          tasksSolved: "28",
          rating: 4.8,
          description: "Инженер DevOps с опытом построения масштабируемой и надежной инфраструктуры",
          fio: "София Гарсия",
          position: "Инженер DevOps",
          age: 31
        },
        {
          userId: 9,
          tasksSolved: "20",
          rating: 4.3,
          description: "Руководитель продукта, руководящий успешными запусками продуктов и стимулирующий рост",
          fio: "Джеймс Родригес",
          position: "Менеджер продукта",
          age: 33
        },
        {
          userId: 10,
          tasksSolved: "35",
          rating: 4.9,
          description: "Аналитик данных с опытом работы в SQL, Python и визуализации данных",
          fio: "Изабелла Лопес",
          position: "Аналитик данных",
          age: 26
        }
      ] as UserStat[],
    tasks: [
        {
          id: 1,
          name: 'Task 1',
          storyPoints: 3,
          description: 'Description 1',
          tags: ['tag1', 'tag2'],
          creatorName: 'Воронова К. К.',
          assigneeName: 'Никольский Ц. Р.',
          status: 'В процессе',
          priority: 'Средний',
        },
        {
          id: 2,
          name: 'Task 2',
          storyPoints: 5,
          description: 'Description 2',
          tags: ['tag3', 'tag4'],
          creatorName: 'Розанова А. Г.',
          assigneeName: 'Митрофанов К. Ф.',
          status: 'К работе',
          priority: 'Высокий',
        },
        {
          id: 3,
          name: 'Task 3',
          storyPoints: 8,
          description: 'Description 3',
          tags: ['tag5', 'tag6'],
          creatorName: 'Самойлова П. С.',
          assigneeName: 'Никонова Л. Г.',
          status: 'Готово',
          priority: 'Низкий',
        },
        {
          id: 4,
          name: 'Task 4',
          storyPoints: 2,
          description: 'Description 4',
          tags: ['tag7', 'tag8'],
          creatorName: 'Шилова А. Н.',
          assigneeName: 'Фомина К. К.',
          status: 'В кодревью',
          priority: 'Высокий',
        },
        {
          id: 5,
          name: 'Task 5',
          storyPoints: 13,
          description: 'Description 5',
          tags: ['tag9', 'tag10'],
          creatorName: 'Мухина Л. А.',
          assigneeName: 'Горшкова Л. М.',
          status: 'В процессе',
          priority: 'Критично',
        },{
          id: 6,
          name: 'Task 6',
          storyPoints: 5,
          description: 'Description 6',
          tags: ['tag11', 'tag12'],
          creatorName: 'Софронова В. М.',
          assigneeName: 'Суворов В. А.',
          status: 'К работе',
          priority: 'Высокий',
        },
        {
          id: 7,
          name: 'Task 7',
          storyPoints: 8,
          description: 'Description 7',
          tags: ['tag13', 'tag14'],
          creatorName: 'Никольский Л. А.',
          assigneeName: 'Евсеева М. Э.',
          status: 'Готово',
          priority: 'Низкий',
        },
        {
          id: 8,
          name: 'Task 8',
          storyPoints: 2,
          description: 'Description 8',
          tags: ['tag15', 'tag16'],
          creatorName: 'Шапошникова Я. Г.',
          assigneeName: 'Рыжова М. Я.',
          status: 'В кодревью',
          priority: 'Высокий',
        },
        {
          id: 9,
          name: 'Task 9',
          storyPoints: 13,
          description: 'Description 9',
          tags: ['tag17', 'tag18'],
          creatorName: 'Никулин В. Л.',
          assigneeName: 'Логинов Э. Э.',
          status: 'В процессе',
          priority: 'Критично',
        },
        {
          id: 10,
          name: 'Task 10',
          storyPoints: 3,
          description: 'Description 10',
          tags: ['tag19', 'tag20'],
          creatorName: 'Прохоров М. С.',
          assigneeName: 'Лосев Ю. И.',
          status: 'В процессе',
          priority: 'Средний',
        },
        {
          id: 11,
          name: 'Task 11',
          storyPoints: 5,
          description: 'Description 11',
          tags: ['tag21', 'tag22'],
          creatorName: 'Зимина С. С.',
          assigneeName: 'Исаков А. С.',
          status: 'К работе',
          priority: 'Высокий',
        },
        {
          id: 12,
          name: 'Task 12',
          storyPoints: 8,
          description: 'Description 12',
          tags: ['tag23', 'tag24'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'Готово',
          priority: 'Низкий',
        },
        {
          id: 13,
          name: 'Task 13',
          storyPoints: 2,
          description: 'Description 13',
          tags: ['tag25', 'tag26'],
          creatorName: 'Игнатьев Н. К.',
          assigneeName: 'Соболев В. Т.',
          status: 'В кодревью',
          priority: 'Высокий',
        },
        {
          id: 14,
          name: 'Task 14',
          storyPoints: 13,
          description: 'Description 14',
          tags: ['tag27', 'tag28'],
          creatorName: 'Филимонова А. Т.',
          assigneeName: 'Носков П. В.',
          status: 'В процессе',
          priority: 'Критично',
        },
        {
          id: 15,
          name: 'Task 15',
          storyPoints: 3,
          description: 'Description 15',
          tags: ['tag29', 'tag30'],
          creatorName: 'Широков А. Д.',
          assigneeName: 'Елисеева О. Л.',
          status: 'В процессе',
          priority: 'Средний',
        },
        {
          id: 16,
          name: 'Task 16',
          storyPoints: 5,
          description: 'Description 16',
          tags: ['tag31', 'tag32'],
          creatorName: 'Прохоров М. С.',
          assigneeName: 'Лосев Ю. И.',
          status: 'К работе',
          priority: 'Высокий',
        },
        {
          id: 17,
          name: 'Task 17',
          storyPoints: 8,
          description: 'Description 17',
          tags: ['tag33', 'tag34'],
          creatorName: 'Зимина С. С.',
          assigneeName: 'Исаков А. С.',
          status: 'Готово',
          priority: 'Низкий',
        },{
          id: 18,
          name: 'Task 18',
          storyPoints: 2,
          description: 'Description 18',
          tags: ['tag35', 'tag36'],
          creatorName: 'Софронова В. М.',
          assigneeName: 'Суворов В. А.',
          status: 'Готово',
          priority: 'Низкий',
        },{
          id: 19,
          name: 'Task 19',
          storyPoints: 13,
          description: 'Description 19',
          tags: ['tag37', 'tag38'],
          creatorName: 'Creator 19',
          assigneeName: 'Assignee 19',
          status: 'В процессе',
          priority: 'Критично',
        },
        {
          id: 20,
          name: 'Task 20',
          storyPoints: 3,
          description: 'Description 20',
          tags: ['tag39', 'tag40'],
          creatorName: 'Самойлова П. С.',
          assigneeName: 'Никонова Л. Г.',
          status: 'В процессе',
          priority: 'Средний',
        },
        {
          id: 21,
          name: 'Task 21',
          storyPoints: 5,
          description: 'Description 21',
          tags: ['tag41', 'tag42'],
          creatorName: 'Самойлова П. С.',
          assigneeName: 'Никонова Л. Г.',
          status: 'К работе',
          priority: 'Высокий',
        },
        {
          id: 22,
          name: 'Task 22',
          storyPoints: 8,
          description: 'Description 22',
          tags: ['tag43', 'tag44'],
          creatorName: 'Самойлова П. С.',
          assigneeName: 'Никонова Л. Г.',
          status: 'Готово',
          priority: 'Низкий',
        },
        {
          id: 23,
          name: 'Task 23',
          storyPoints: 2,
          description: 'Description 23',
          tags: ['tag45', 'tag46'],
          creatorName: 'Самойлова П. С.',
          assigneeName: 'Никонова Л. Г.',
          status: 'В кодревью',
          priority: 'Высокий',
        },
        {
          id: 24,
          name: 'Task 24',
          storyPoints: 13,
          description: 'Description 24',
          tags: ['tag47', 'tag48'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'В процессе',
          priority: 'Критично',
        },
        {
          id: 25,
          name: 'Task 25',
          storyPoints: 3,
          description: 'Description 25',
          tags: ['tag49', 'tag50'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'В процессе',
          priority: 'Средний',
        },
        {
          id: 26,
          name: 'Task 26',
          storyPoints: 5,
          description: 'Description 26',
          tags: ['tag51', 'tag52'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'К работе',
          priority: 'Высокий',
        },
        {
          id: 27,
          name: 'Task 27',
          storyPoints: 8,
          description: 'Description 27',
          tags: ['tag53', 'tag54'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'Готово',
          priority: 'Низкий',
        },
        {
          id: 28,
          name: 'Task 28',
          storyPoints: 2,
          description: 'Description 28',
          tags: ['tag55', 'tag56'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'В кодревью',
          priority: 'Высокий',
        },
        {
          id: 29,
          name: 'Task 29',
          storyPoints: 13,
          description: 'Description 29',
          tags: ['tag57', 'tag58'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'В процессе',
          priority: 'Критично',
        },
        {
          id: 30,
          name: 'Task 30',
          storyPoints: 3,
          description: 'Description 30',
          tags: ['tag59', 'tag60'],
          creatorName: 'Львов Я. П.',
          assigneeName: 'Коновалова Е. О.',
          status: 'В процессе',
          priority: 'Средний',
        }
      ] as Task[],
    comments: [
      { id: 1, text: 'Вот это да!', user: 'Большая бабочка' },
      { id: 2, text: 'Вопросики по решению', user: 'Крутой тимлид' }
    ] as Comment[
      ],
    userProfile: null as UserProfile | null,
    registredUsers: [] as UserProfile[] | null,

  }),
  actions: {
    logout() {
      this.userProfile = null;
    }
  }
});