version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /path/to/local/postgres/data:/var/lib/postgresql/data
      - /path/to/local/scripts:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_connections=200"]
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
  app:
    links:
      - postgres:postgres
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
